# Generated by Django 3.1.3 on 2020-11-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201126_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='height_field',
            new_name='logo_height_field',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='width_field',
            new_name='logo_width_field',
        ),
        migrations.RenameField(
            model_name='specialty',
            old_name='height_field',
            new_name='picture_height_field',
        ),
        migrations.RenameField(
            model_name='specialty',
            old_name='width_field',
            new_name='picture_width_field',
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(height_field='logo_height_field', upload_to='company_images', width_field='logo_width_field'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(height_field='picture_height_field', upload_to='speciality_images', width_field='picture_width_field'),
        ),
    ]
